"""Talking to Vibe: prompt, agent profile, command line, output and session stats.

Vibe behaviour relied on (checked against mistral-vibe 2.25.x):
  * `--output json` prints a JSON list of history entries (camelCase keys).
  * In programmatic mode, any tool call that needs approval is denied.
  * Custom agent profiles are TOML files in $VIBE_HOME/agents/<name>.toml. They
    can set `active_model` and per-tool permissions, including
    `[tools.bash] allowlist` (command prefixes; every part of a compound
    command must match for it to be auto-approved).
  * Hitting --max-turns / --max-price / --max-tokens exits 1 with the last
    assistant text on stderr and nothing on stdout.
  * Each session writes $VIBE_HOME/logs/session/<prefix>_<time>_<id[:8]>/meta.json
    whose "stats" include session_cost, steps and token counts.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

READ_ONLY_TOOLS = ["read_file", "grep", "todo"]

# Vibe's default bash allowlist (POSIX). A profile's allowlist replaces it, so keep it.
DEFAULT_BASH_ALLOWLIST = [
    "cd", "echo", "git diff", "git log", "git status", "tree", "whoami",
    "basename", "cat", "comm", "cut", "date", "diff", "dirname", "du", "file", "find", "fmt",
    "fold", "grep", "head", "join", "less", "ls", "md5sum", "more", "nl", "od", "paste", "pwd",
    "readlink", "sha1sum", "sha256sum", "shasum", "sort", "stat", "sum", "tac", "tail", "tr",
    "uname", "uniq", "wc", "which",
]

MAX_SPEC_CHARS = 20_000


def vibe_home() -> Path:
    home = os.environ.get("VIBE_HOME")
    return Path(home).expanduser() if home else Path.home() / ".vibe"


# Model aliases Vibe ships with; users add more under [[models]] in $VIBE_HOME/config.toml.
BUILTIN_MODEL_ALIASES = {"mistral-medium-3.5", "local"}


def unknown_model_warning(model: str | None) -> str | None:
    """Vibe silently falls back to its default model for an alias it doesn't know; say so."""
    if not model:
        return None
    try:
        import tomllib
        with (vibe_home() / "config.toml").open("rb") as f:
            data = tomllib.load(f)
    except (ImportError, OSError):
        data = {}
    except ValueError:
        return None
    aliases = BUILTIN_MODEL_ALIASES | {m.get("alias") for m in data.get("models", []) if isinstance(m, dict)}
    if model in aliases:
        return None
    return (f"model {model!r} is not in Vibe's configured models ({', '.join(sorted(a for a in aliases if a))}); "
            "Vibe falls back to its default model. Add it under [[models]] in ~/.vibe/config.toml.")


def _toml_str(value: str) -> str:
    return json.dumps(value)  # JSON string escapes are valid TOML basic-string escapes.


def write_agent_profile(mode: str, model: str | None, allow_commands: list[str]) -> str | None:
    """Write a Vibe agent profile for this run and return its name, or None to use a built-in agent."""
    if mode == "read" and not model:
        return None
    lines = [
        'display_name = "Claude delegate"',
        'description = "Generated by the mistral-delegate Claude Code plugin"',
        'disabled_tools = ["exit_plan_mode"]',
    ]
    if model:
        lines.append(f"active_model = {_toml_str(model)}")
    edit_permission = "always" if mode == "write" else "never"
    lines += ["", "[tools.write_file]", f'permission = "{edit_permission}"',
              "", "[tools.edit]", f'permission = "{edit_permission}"']
    if mode == "write":
        allowlist = list(dict.fromkeys(DEFAULT_BASH_ALLOWLIST + allow_commands))
        lines += ["", "[tools.bash]", "allowlist = [" + ", ".join(_toml_str(c) for c in allowlist) + "]"]
    content = "\n".join(lines) + "\n"

    name = f"claude-delegate-{hashlib.sha1(content.encode()).hexdigest()[:10]}"
    path = vibe_home() / "agents" / f"{name}.toml"
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(f".{os.getpid()}.tmp")
        tmp.write_text(content)
        tmp.replace(path)
    return name


def build_prompt(task: str, *, mode: str, spec: str | None, context: list[str], verify: list[str],
                 allow_commands: list[str], allow_shell: bool) -> str:
    parts = [task.strip()]
    if spec:
        if len(spec) > MAX_SPEC_CHARS:
            spec = spec[:MAX_SPEC_CHARS] + "\n[... spec truncated ...]"
        parts.append("## Spec\n\n" + spec.strip())
    if context:
        parts.append("## Read these files first\n\n" + "\n".join(f"- {c}" for c in context))

    if mode == "write":
        rules = []
        if allow_shell:
            rules.append("You may run shell commands.")
        elif allow_commands:
            rules.append("You may run these shell commands yourself (other commands will be refused): "
                         + ", ".join(f"`{c}`" for c in allow_commands) + ".")
        else:
            rules.append("Shell commands will be refused, so don't try to run anything; just write the code.")
        if verify:
            rules.append("When you finish, these checks will be run, and they must pass: "
                         + ", ".join(f"`{c}`" for c in verify) + ".")
        rules += [
            "Don't install, upgrade or remove packages: dependency folders are shared with the user's checkout.",
            "Only change what the task needs. Don't delete or weaken existing tests.",
            "Finish with a short list of every file you changed and why, then anything you couldn't do.",
        ]
        parts.append("## Rules\n\n" + "\n".join(f"- {r}" for r in rules))
    return "\n\n".join(parts)


def fix_prompt(command: str, exit_code: int, output: str) -> str:
    return (
        f"The check `{command}` failed (exit code {exit_code}). The end of its output:\n\n"
        f"```\n{output}\n```\n\n"
        "Fix the code so this check passes. Don't change the check, and don't delete or weaken tests "
        "to make it pass. Finish with the files you changed and what you fixed."
    )


def build_command(vibe_bin: str, prompt: str, *, mode: str, agent: str | None, caps: dict,
                  allow_shell: bool, trust: bool, resume: str | None) -> list[str]:
    cmd = [
        vibe_bin,
        "--prompt", prompt,
        "--output", "json",
        "--max-turns", str(caps["max_turns"]),
        "--max-price", f"{caps['max_price']:.4f}",
    ]
    if caps.get("max_tokens"):
        cmd += ["--max-tokens", str(caps["max_tokens"])]
    cmd += ["--agent", agent or ("plan" if mode == "read" else "accept-edits")]
    if mode == "read":
        for tool in READ_ONLY_TOOLS:
            cmd += ["--enabled-tools", tool]
    elif allow_shell:
        cmd += ["--auto-approve"]
    if trust:
        cmd += ["--trust"]
    if resume:
        cmd += ["--resume", resume]
    return cmd


def text_of(entry: dict) -> str:
    return "\n\n".join(
        block.get("text", "")
        for block in entry.get("content") or []
        if isinstance(block, dict) and block.get("type") == "text"
    ).strip()


def summarize_history(history: list) -> dict:
    session_id = None
    final_text = ""
    tool_calls = 0
    problems: list[str] = []
    notices: list[str] = []

    for entry in history:
        if not isinstance(entry, dict):
            continue
        session_id = session_id or entry.get("sessionId")
        kind = entry.get("type")
        if kind == "message" and entry.get("role") == "assistant":
            text = text_of(entry)
            if text:
                final_text = text
        elif kind == "effect":
            tool_calls += 1
            state = entry.get("state") or {}
            status = state.get("status")
            if status not in ("completed", None):
                reason = state.get("reason") or (state.get("error") or {}).get("message") or ""
                problems.append(f"{entry.get('title', 'tool')}: {status}" + (f" ({reason})" if reason else ""))
            elif status == "completed" and state.get("decision") == "skip":
                problems.append(f"{entry.get('title', 'tool')}: skipped (not approved)")
        elif kind == "notice" and entry.get("level") in ("warning", "error"):
            notices.append(f"{entry.get('level')}: {entry.get('message', '')}")

    return {"session_id": session_id, "final_text": final_text, "tool_calls": tool_calls,
            "problems": problems, "notices": notices}


def parse_output(stdout: str) -> list:
    stdout = stdout.strip()
    if not stdout:
        return []
    try:
        data = json.loads(stdout)
    except json.JSONDecodeError:
        start = stdout.find("[")  # Tolerate stray lines before the JSON payload.
        if start == -1:
            return []
        try:
            data = json.loads(stdout[start:])
        except json.JSONDecodeError:
            return []
    if isinstance(data, dict):
        data = data.get("history", [])
    return data if isinstance(data, list) else []


def read_session_stats(session_id: str | None, cwd: str, since: float | None = None) -> dict | None:
    """Find a session's stats in Vibe's session log.

    With a session id, match it exactly. Without one (e.g. when a limit stopped the
    run and nothing was printed), take the newest session written since `since`
    for the same working directory.
    """
    log_dir = vibe_home() / "logs" / "session"
    if not log_dir.is_dir():
        return None
    if session_id:
        metas = list(log_dir.glob(f"*_{session_id[:8]}/meta.json"))
    else:
        dirs = sorted((d for d in log_dir.iterdir() if d.is_dir()), key=lambda d: d.stat().st_mtime)[-50:]
        metas = [d / "meta.json" for d in dirs]
    for meta_path in sorted(metas, key=lambda m: m.stat().st_mtime if m.exists() else 0, reverse=True):
        try:
            if since is not None and meta_path.stat().st_mtime < since - 1:
                continue
            meta = json.loads(meta_path.read_text())
        except (OSError, ValueError):
            continue
        if session_id and meta.get("session_id") != session_id:
            continue
        workdir = (meta.get("environment") or {}).get("working_directory")
        if not session_id and workdir and Path(workdir).resolve() != Path(cwd).resolve():
            continue
        stats = meta.get("stats")
        if isinstance(stats, dict):
            return {"session_id": meta.get("session_id"), **stats}
    return None


def stats_cost(stats: dict | None) -> float:
    if not stats:
        return 0.0
    if "session_cost" in stats:
        return float(stats["session_cost"])
    prompt = stats.get("session_prompt_tokens", 0)
    cached = min(stats.get("session_cached_tokens", 0), prompt)
    in_price = stats.get("input_price_per_million", 0.0)
    cached_price = stats.get("cached_input_price_per_million")
    cached_price = in_price if cached_price is None else cached_price
    out = stats.get("session_completion_tokens", 0) * stats.get("output_price_per_million", 0.0)
    return ((prompt - cached) * in_price + cached * cached_price + out) / 1_000_000


def usage(after: dict | None, before: dict | None) -> dict | None:
    """This run's cost, steps and tokens (after minus before, for resumed sessions)."""
    if not after:
        return None
    before = before or {}
    return {
        "cost": stats_cost(after) - (stats_cost(before) if before else 0.0),
        "steps": after.get("steps", 0) - before.get("steps", 0),
        "tokens": (after.get("session_prompt_tokens", 0) + after.get("session_completion_tokens", 0)
                   - before.get("session_prompt_tokens", 0) - before.get("session_completion_tokens", 0)),
        "session_total": stats_cost(after) if before else None,
    }
